# Generated by Django 5.0 on 2023-12-24 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='project',
            new_name='projectId',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='task_ID',
            new_name='taskId',
        ),
    ]
