# Generated by Django 5.0 on 2023-12-24 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(default='Ongoing', max_length=20),
            preserve_default=False,
        ),
    ]
