# Generated by Django 5.0 on 2024-01-02 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_priority'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
